# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Health Data Working Group"
title:              "Health Data Working Group at the Dalla Lana School of Public Health, University of Toronto"
description:        "this is a page for Health Data Working group. We are a group comprised of students and faculty members from the School of Public Health with an interest in providing programming-related tools for public health research."


# URL
url:                http://health-data-working-group.github.io/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /workshops/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

future: true

# Navigation
nav:
  - name:           "home"
    href:           "/"
  # - name:           "about"
  #   href:           "/about"
  # - name:           "publications"
  #   href:           "/publication"
  - name:           "workshops"
    href:           "/workshops/"
  - name:           "people"
    href:           "/people"
  # - name:           "blog"
  #   href:           "/blog"
  # - name:           "resources"
  #   href:           "/resources"

responsive_image:
  template: _includes/responsive_img.html
  # Quality to use when resizing images.
  default_quality: 80
  sizes:
    - width: 480
    - width: 800
    - width: 1400
      quality: 90
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size.
  strip: true


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
  workshops:
    output: true
    permalink: /workshops/:title.html